Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # Réseau privé pour Ansible
  config.vm.network "private_network", ip: "192.168.56.10"

  # Clé SSH stable (globale)
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end
end
