Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.network "private_network", ip: "192.168.56.10"
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  # Provision via Ansible automatiquement
#  config.vm.provision "ansible" do |ansible|
 #   ansible.playbook = "../ansible/playbook.yml"
  #  ansible.inventory_path = "../ansible/inventory/hosts.ini"
   # ansible.limit = "default"
 # end
end
